# Generated by Django 5.2.5 on 2025-08-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tradingsymbol', models.CharField(max_length=50)),
                ('instrument_key', models.CharField(max_length=100)),
            ],
        ),
    ]
