# Generated by Django 5.2.4 on 2025-08-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('change', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percent_change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.BigIntegerField()),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_top_gainer', models.BooleanField(default=False)),
                ('is_top_loser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('change', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percent_change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
