# Generated by Django 5.2.4 on 2025-08-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
