# Generated by Django 5.2.4 on 2025-08-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_portfolio_company_name_portfolio_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='company_name',
            field=models.CharField(blank=True, default='Unknown Company', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
